name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SPRING_PROFILES_ACTIVE: test
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app

      - name: Run tests
        working-directory: ./app
        run: ./gradlew test

      - name: Generate coverage report
        run: make report

      - name: Upload to Qlty.sh
        uses: qltysh/qlty-action/coverage@v1
        with:
          files: /home/runner/work/java-project-99/java-project-99/app/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        working-directory: ./app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info

      - name: Upload source context to Sentry
        if: github.ref == 'refs/heads/main'
        working-directory: ./app
        run: ./gradlew sentryBundleSources --info
        env:
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
            ORG_GRADLE_PROJECT_sentryAuthToken: ${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_LOG_LEVEL: debug

      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        working-directory: ./app
        run: |
          docker build -t my-app:latest ./app
          echo "SENTRY_DSN=$SENTRY_DSN" >> .env
          echo "SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN" >> .env
